### PR TITLE
Added API for disconnecting from the slack server

### PR DESCRIPTION
**Pull request by janvidar**
I was working on a small service bot that would post certain event messages to slack, however I noticed there was no API for disconnecting which caused some hanging java processes due to the connection monitor thread.

This is an attempt at creating a disconnect() method in the same fashion as the connect() method that would disconnect the websocket connection, and shut down the monitor thread.

### CODE REVIEW

**Comment by bcorne** [comment]
Hi,

That looks good, thanks, I merge it. 

Would you like to be added in the contributors list? If so just give me a name, an email and an URL to a personal website (email and URL are not mandatory of course) so this will be included in the pom.xml of the next release.

Best regards,

Benoit

**Comment by janvidar** [comment]
Hi thanks, this was fast :)

You can use my name "Jan Vidar Krey" and e-mail address janvidar *at* extatic.org. No website necessary.

**Comment by bcorne** [comment]
Ok, done. 

Let me know if you're having some troubles or idea with this library.

Best regards,

Benoit

**Comment by janvidar** [comment]
Great, I'll do that.
I see that there are some problems already after using it for half a day. I'll post some more pull requests, if you don't mind.

**Comment by bcorne** [comment]
Of course I don't mind. 

I'll have a look at it with pleasure.

Best regards,

Benoit

**Pull request merged**
