### PR TITLE
Add legacyMode to use rtm.connect

### PR DESCRIPTION
**Pull request by nhaquet2**
rtm.connect used instead of app connection
following deprecation of rtm.start

legacyMode is the default mode

Change-Id: I5b38877986ec952cf7abdc1a2cd1befe3cdafe1e

### CODE REVIEW

**Review by josselinchevalay — APPROVED** [review]

**Comment by FranciscoRuiz-FT** [comment]
Hello @bcorne / @josselinchevalay, thank you very much for bringing these changes in, will they be released to any specific library version?

**Comment by tanu3195** [comment]
> rtm.connect used instead of app connection following deprecation of rtm.start
> 
> legacyMode is the default mode
> 
> Change-Id: I5b38877986ec952cf7abdc1a2cd1befe3cdafe1e

Hi All,

We are using the below image so do we have any updated image at docker hub with the latest changes?

outofcoffee/corebot-generic:1.3.0

Regards,

**Comment by bcorne** [comment]
> Hello @bcorne / @josselinchevalay, thank you very much for bringing these changes in, will they be released to any specific library version (I mean maven central)? Sorry, I'm not very familiar with the lifecycle 😊

Hello @FranciscoRuiz-FT 

We've just done the release. It should be available soon on maven central

Best regards,

Benoit

**Comment by josselinchevalay** [comment]
Hello @tanu3195, 

We are not the maintainer of the image outofcoffee/corebot-generic what we have just done and release 1.4.0 I invite you to approach to make an issue so that it upgrades the version of simplelackapi and republish an updated docker image on their project : https://github.com/outofcoffee/corebot/issues 

Regards

**Comment by tanu3195** [comment]
@josselinchevalay Thanks for the reply.

I have opened the issue there 7 days back but let me update along with recommendations above.

https://github.com/outofcoffee/corebot/issues/61

**Pull request merged**
