### PR TITLE
some functional changes

### PR DESCRIPTION
**Pull request by kindofwhat**
* persons and bots are both "persona", i.e. share some common attributes
* base implementation of slack presences
* channels can be direct (persona to persona) or shared
* a slack session is accordingly attached to a persona (either bot or person)
* fallback dispatch: if it is a slackmessage, dispatch to this

cosmetic:
* consolidated import statement (more wildcards)
* some toString implementations

This is my first pull request ever. If I did something wrong, I am very open for directions and corrections. I like your library very much, it is clear and concise.

### CODE REVIEW

**Comment by bcorne** [comment]
Thanks a lot for your contribution, I'll have a look as soon as possible :)

**Comment by kindofwhat** [comment]
Please consider also 
https://github.com/Ullink/simple-slack-api/commit/c9f65bfb7f066d9e9b35ca9cce96604d78af5533
to have the tests running again. Didn't run anymore, culpa mea

**Comment by bcorne** [comment]
That looks good, thanks a lot, you even fixed the message dispatch issue I introduced in the last commit I made. It's time to add the contributor section in the POM of this library, would you like to be added to it ?

**Comment by kindofwhat** [comment]
oh *blush* if you feel like, I would be honored

**Comment by bcorne** [comment]
Yes of course, since you contributed you deserve it.

I'll need to have some information though : 

name, 
email, 
url,
organization, 
organization URL

none of them are mandatory of course :)

**Pull request merged**
