### PR TITLE
Add im channels to the channel list

### PR DESCRIPTION
**Pull request by dseebacher**
As stated this change adds all im channels to the already existing channel list. This results in more channels than before and could change (break) behavior. 
An alternative would be a separate im channel list...

### CODE REVIEW

**Comment by bcorne** [comment]
Many thanks, would you like to be added to the contributors list?

**Comment by dseebacher** [comment]
Sure, thx :)

**Comment by bcorne** [comment]
Good, 

So, which name, email and url (not mandatory of course) should I have to add to the pom?

Best regards,

Benoit

**Comment by dseebacher** [comment]
Here u go:

David Seebacher
dseebacher@gmail.com
https://github.com/dseebacher

- David

**Pull request merged**
