### PR TITLE
Added Slack API rate limit support

### PR DESCRIPTION
**Pull request by msagi**

### CODE REVIEW

**Comment by msagi** [comment]
Sure, I'll change it to be configurable and move this logic to a separate, pluggable class

**Comment by msagi** [comment]
Implemented the rate limit support as a custom retry strategy which is enabled by default but can be opted-out.

**Comment by msagi** [comment]
@tekknick can you take a second look?

**Comment by tekknick** [comment]
Sure @msagi. It's great to have the option to opt-out of the automatic retry. If you changed the type of `boolean isRateLimitSupported` to `ServiceUnavailableRetryStrategy` it would make this improvement much more powerful -- 'cause clients could plug in their own strategies – but as it is now, it meets my teams' needs. Thank you.

**Comment by bcorne** [comment]
Hi, 

Many thanks for your contribution. Don't forget to add yourself in the contributors list

**Pull request merged**
